#!/usr/bin/env bash
# Script that displays information about subdomains given a domain and a subdomain
# Usage: ./0-world_wide_web example.com www

domain_info () {
    # Define an array of subdomains
    subdomains=("www" "lb-01" "web-01" "web-02")

    # Check if a subdomain is given as the second argument ($2)
    if [ -z "$2" ]; then
        # If ($2) is empty, loop through all subdomains in the subdomains array
        for subdomain in "${subdomains[@]}"; do
            result=$(dig "$subdomain.$1" +short)
            if [ -n "$result" ]; then
                echo "The subdomain $subdomain is a $(dig "$subdomain.$1" +short -t CNAME) record and points to $result"
            else
                echo "The subdomain $subdomain does not exist."
            fi
        done
    else
        # If ($2) is not empty, print the information about the given subdomain ($2)
        result=$(dig "$2.$1" +short)
        if [ -n "$result" ]; then
            echo "The subdomain $2 is a $(dig "$2.$1" +short -t CNAME) record and points to $result"
        else
            echo "The subdomain $2 does not exist."
        fi
    fi
}

# Check for the correct number of arguments
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <domain> <subdomain>"
    exit 1
fi

# Call the domain_info function with the first argument ($1) as the domain and the second argument ($2) as the subdomain
domain_info "$1" "$2"
