#!/urs/bin/env bash
# checking for command line arguments
# Transfers a file from our client to server.
# Accepts four parameters:
# . 1 The path to the file to be transferred.
# . 2  The IP of the server to transfer the file to.
# . 3 The username that scp connects with.
# . 4 The path to the SSH private key that scp uses.
# . 5 Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
# . 6 scp must transfer the file to the user home directory ~/
# . 7 Strict host key checking must be disabled when using scp

#checks if the number of argument is less than 4
if [ $# -lt 4 ]
then
#print usage
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit 1
fi

# assigning paramentals to variables

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# disabling strict host key checking

scp -0 "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# checking if the transfer was successful
if [ $? -eq 0 ]
then
        echo "FILE WAS TRANSFERED SUCCESSFULLY"
else
        echo "FILE TRANSFER FAILED"
fi
