#!/usr/bin/env bash
# command to install nginx on web server

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# testing nginx config for successful
sudo nginx -t

# to reload or restart for effect to take place in html
sudo service nginx reload

